[package]
name = "node"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }
